name: Gemtek MXF-W1700K Bootloader
device: EFR32MG21A010F512IM32
base_project: src/bootloader
filename: "{manifest_name}_{gecko_bootloader_version}"
sdk: "gecko_sdk:4.5.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: gecko-bootloader
  gecko_bootloader_version: dynamic
  baudrate: 115200

# A bootloader posted to OpenWrt forum bumped the major version from 2 to 3.
# Anti-rollback prevents flashing the 2.x bootloaders that current SDKs
# produce, there's no guard on the defines, meaning we must patch the SDK
# to builder a bootloader with a higher version that can be flashed over it.
sdk_patches:
  - btl_config_version_override.patch

c_defines:
  BOOTLOADER_VERSION_MAIN_CUSTOMER: 4

  SL_SERIAL_UART_FLOW_CONTROL: 0

  SL_SERIAL_UART_PERIPHERAL: USART0
  SL_SERIAL_UART_PERIPHERAL_NO: 0

  SL_SERIAL_UART_TX_PORT: gpioPortA
  SL_SERIAL_UART_TX_PIN:  5

  SL_SERIAL_UART_RX_PORT: gpioPortA
  SL_SERIAL_UART_RX_PIN:  6


  SL_GPIO_ACTIVATION_POLARITY: LOW
  SL_BTL_BUTTON_PORT: gpioPortC
  SL_BTL_BUTTON_PIN: 5
